// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Health struct {
	Status  string `json:"status"`
	Service string `json:"service"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}
